# Generated by Django 4.2.3 on 2023-07-25 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('food', models.CharField(max_length=50)),
                ('study', models.CharField(max_length=50)),
                ('work1', models.CharField(max_length=50)),
                ('work2', models.CharField(max_length=50)),
                ('housing', models.CharField(max_length=50)),
                ('health', models.CharField(max_length=50)),
                ('salary', models.CharField(max_length=50)),
                ('debt', models.CharField(max_length=50)),
                ('other', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('limitDate', models.DateField()),
                ('priority', models.CharField(choices=[('fundamental', 'Fundamental'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=15)),
                ('finState', models.BooleanField(default=False)),
                ('ejecState', models.BooleanField(default=False)),
            ],
        ),
    ]
