# Generated by Django 4.2.3 on 2023-07-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWebFin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
